GET http://localhost:3001/books HTTP/1.1 
Content-Type: application/JSON

###
POST http://localhost:3001/books HTTP/1.1 
Content-Type: application/JSON

{
    "title": "The Road"
}

###
PUT http://localhost:3001/books/1 HTTP/1.1 
Content-Type: application/JSON

{
    "title": "The Rainbow Road"
}

###
DELETE http://localhost:3001/books/1 HTTP/1.1 
Content-Type: application/JSON
